### ISSUE TITLE
Unable to add Hyperlink

### ISSUE THREAD

**Issue by mcrpl** [wanglin2/mind-map#22]
Hi sir, @wanglin2 , while adding a hyperlink ( with http:// ) in the node, unable to add // (Slash) in the hyperlink text area sir. even i tried copying and pasting hyperlinks in the hyperlink text area. but can't do it sir
is there any other way to add a hyperlink in the node?

**Comment by mcrpl** [comment]
we have already a "/" hotkey shortcut to Expand/collapse node.. this feature interferes with the hyperlink [// (slash)] feature, sir...

**Comment by wanglin2** [comment]
Hello, it has been fixed

**Comment by mcrpl** [comment]
sir @wanglin2 , the same way, it does not allow adding capital English letter sir, (such as adding Capital "L" by pressing Shift + L [as there is a shortcut]) and also **while editing text in the node, Delete and/or Backspace and/or Control(Ctrl) and/or Shift keys didn't work properly**. as there are interferences with hotkeys sir...

**Comment by wanglin2** [comment]
These two bugs have been fixed. You can have a try

**Comment by mcrpl** [comment]
This works fine @wanglin2  sir.. thank you sir

**Comment by mcrpl** [comment]
Hi sir.. i can see you have changed the Auto-align shortcut (form Shift + L to Ctrl + L) but you dint forget to update the file sir... as you can see in the **right-click menu it still showing Shift + L** and in the **hotkey chart it showing Ctrl + L**
![image](https://user-images.githubusercontent.com/110148926/184934559-47711b87-94aa-4f74-8f5d-2198e3f369fc.png)

**Comment by wanglin2** [comment]
Has been modified
